name: Metrics

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - name: Isometric commit calendar (full year)
              uses: lowlighter/metrics@latest
              with:
                                    token: ${{ secrets.METRICS_TOKEN || github.token }}
                  user: piyushsarkar-dev
                  template: classic
                  base: ""
                  filename: .github/metrics/isocalendar.svg
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: full-year
                  output_action: commit
                  committer_branch: main
                  committer_message: "chore: update metrics (isocalendar full-year)"

            - name: Isometric commit calendar (half year)
              uses: lowlighter/metrics@latest
              with:
                                    token: ${{ secrets.METRICS_TOKEN || github.token }}
                  user: piyushsarkar-dev
                  template: classic
                  base: ""
                  filename: .github/metrics/isocalendar-half-year.svg
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year
                  output_action: commit
                  committer_branch: main
                  committer_message: "chore: update metrics (isocalendar half-year)"

            - name: Languages activity
              uses: lowlighter/metrics@latest
              with:
                                    token: ${{ secrets.METRICS_TOKEN || github.token }}
                  user: piyushsarkar-dev
                  template: classic
                  base: ""
                  filename: .github/metrics/languages.svg
                  plugin_languages: yes
                  plugin_languages_indepth: yes
                  plugin_languages_details: bytes-size, percentage
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  output_action: commit
                  committer_branch: main
                  committer_message: "chore: update metrics (languages)"
