name: Metrics

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - .github/workflows/metrics.yml
    schedule:
        - cron: "0 0 * * *"

permissions:
    contents: write

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - name: Isometric Calendar only
              uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN || github.token }}

                  committer_token: ${{ github.token }}
                  user: piyushsarkar-dev
                  template: classic
                  base: ""
                  filename: .github/metrics/metrics.svg
                  repositories_affiliations: owner, collaborator, organization_member
                  repositories_forks: no
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year
                  output_action: commit
                  committer_branch: main
                  committer_message: "chore: update isometric calendar only"
